---
apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: go-mongodb           # Name of the Kubernetes resource
spec:
  replicas: 3                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: go-mongodb        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: go-mongodb 
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: go-mongodb
        image: sankproject/go-mongodb:1.0.0 
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000  # Should match the port number that the Go application listens on  
---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: go-mongodb-service   # Name of the resource
spec:
  type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
  - name: http
    port: 9091
    targetPort: 8000
    nodePort: 30037
  selector:
    app: go-mongodb         # Map any pod with label `app=go-hello-world` to this service
